"""Onboarding flow — generates initial CLAUDE.md + starter lairs from a short questionnaire.

Designed to be run once on a new machine / project, after `lbrain init`. The questions are
short, opinionated, and produce a working lair scaffold so users don't have to think about
the protocol on day one.
"""

from __future__ import annotations

import datetime
from pathlib import Path

import click

STARTER_RULES = """# LAIR_RULES (LBrain default)

- **300-line cap** per LAIR.md. Extract session logs to `sessions/` subfolder.
- **Format**: tables over prose, front-load status in first 30 lines.
- **Naming**: `000-PRIORITY-NAME/` for high-priority, `kebab-case/` for standard.
- **Staleness**: 0-30 days = active, 30-60 = flag for audit, 60+ = archive candidate.
- **Audit cadence**: biweekly (every other Tuesday).
- **Wikilinks**: cross-reference related lairs with `[[lair-slug]]`.
"""

STARTER_TEMPLATE = """# LAIR: {name}

**Status**: PLANNING
**Priority**: MEDIUM
**Last Updated**: {date}
**Mission**: {mission}

---

## Current State

| Aspect | Status | Notes |
|---|---|---|
| (component) | (status) | (note) |

**Blocked by**: Nothing
**Next action**: (next step)

---

## Decisions Log

- **{date}**: Lair created from onboarding questionnaire.

---

## Implementation Checklist

- [ ] First task
- [ ] Second task

---

## Related Lairs

| Lair | Relationship |
|---|---|
| `[[lair-name]]` | (how it connects) |

---

*One-line motto here.*
"""


def run_onboarding(target_dir: Path) -> Path:
    """Interactive onboarding. Returns the path to the generated CLAUDE.md."""
    click.secho("\n🧠 LBrain Onboarding — by Metavolve Labs\n", fg="cyan", bold=True)
    click.echo("Three minutes. We'll scaffold a working lair system for you.\n")

    project = click.prompt("Project name", type=str)
    one_liner = click.prompt("What does it do? (one sentence)", type=str)
    domain = click.prompt(
        "Primary domain (e.g. 'web app', 'data pipeline', 'research', 'agent system')",
        type=str,
    )
    stack = click.prompt("Stack (e.g. 'Python + FastAPI + Postgres')", type=str)
    biggest_risk = click.prompt(
        "What's the biggest thing that could go wrong if you forget it later?", type=str
    )
    starter_priorities = click.prompt(
        "Three top priorities right now (comma-separated)", type=str
    ).split(",")
    starter_priorities = [s.strip() for s in starter_priorities if s.strip()]

    target_dir.mkdir(parents=True, exist_ok=True)
    lairs_dir = target_dir / "lairs"
    lairs_dir.mkdir(exist_ok=True)
    (lairs_dir / "LAIR_RULES.md").write_text(STARTER_RULES, encoding="utf-8")

    today = datetime.date.today().isoformat()

    # Generate CLAUDE.md
    claude_md = f"""# CLAUDE.md — {project}

**One-liner**: {one_liner}
**Domain**: {domain}
**Stack**: {stack}
**Started tracking**: {today}

---

## Top priorities (set during onboarding {today})

"""
    for i, p in enumerate(starter_priorities[:3], 1):
        slug = _kebab(p)
        claude_md += f"{i}. **{p}** — see `lairs/000-PRIORITY-{slug}/LAIR.md`\n"

    claude_md += f"""

---

## The biggest thing not to forget

{biggest_risk}

---

## Lair system

This project uses the **Lair Protocol** for session-resumable engineering memory:

- `lairs/LAIR_RULES.md` — governance
- `lairs/000-PRIORITY-*/` — high-priority work
- `lairs/<kebab-case-name>/` — standard tracking lairs

When you (or an AI agent) finish a session, the agent should ask:
> *"Is anything here worth committing to a lair?"*

LBrain's `lair_protocol_check` tool answers this automatically. Run `lbrain query <topic>` to
search across all lairs semantically.

---

## Commands

```bash
lbrain query "your question"
lbrain search "exact keyword"
lbrain import lairs/
lbrain embed --stale
```

---

*Generated by LBrain by Metavolve Labs on {today}.*
"""
    claude_path = target_dir / "CLAUDE.md"
    claude_path.write_text(claude_md, encoding="utf-8")

    # Generate starter priority lairs
    for p in starter_priorities[:3]:
        slug = _kebab(p)
        lair_dir = lairs_dir / f"000-PRIORITY-{slug}"
        lair_dir.mkdir(exist_ok=True)
        (lair_dir / "LAIR.md").write_text(
            STARTER_TEMPLATE.format(name=p.upper(), date=today, mission=f"Track {p}."),
            encoding="utf-8",
        )

    # Generate a default standard lair: "session-log"
    standard_dir = lairs_dir / "session-log"
    standard_dir.mkdir(exist_ok=True)
    (standard_dir / "LAIR.md").write_text(
        STARTER_TEMPLATE.format(
            name="Session Log",
            date=today,
            mission="Capture session-by-session notes that don't fit other lairs.",
        ),
        encoding="utf-8",
    )

    click.secho(f"\n✓ Scaffolded {len(starter_priorities[:3]) + 1} lairs + CLAUDE.md", fg="green")
    click.secho(f"  → {target_dir}\n", fg="green")
    click.echo("Next steps:")
    click.echo(f"  1. lbrain import {lairs_dir}")
    click.echo("  2. lbrain embed --stale")
    click.echo('  3. lbrain query "your first question"')

    return claude_path


def _kebab(s: str) -> str:
    import re

    return "-".join(re.findall(r"[A-Za-z0-9]+", s.upper()))
